import * as Popover from "@radix-ui/react-popover";
import { ChevronRight } from "lucide-react";
import { StageDetail } from "./StageDetail";
import type { AgentStepView, TraceView } from "../../lib/types";
import { humanizeLabel, humanizeNode } from "../../lib/presenters";
import { agentVisual, tracePhase } from "./AgentShared";

interface AgentTimelineProps {
  trace: TraceView | null;
  displayedSteps: AgentStepView[];
  selectedStepIndex: number;
  latestVisibleStepIndex: number;
  actionLoading: string | null;
  refreshing: boolean;
  executionComplete: boolean;
  onSelectStep: (index: number) => void;
}

export function AgentTimeline({
  trace,
  displayedSteps,
  selectedStepIndex,
  latestVisibleStepIndex,
  actionLoading,
  refreshing,
  executionComplete,
  onSelectStep,
}: AgentTimelineProps) {
  return (
    <section className="space-y-5">
      <div>
        <h2 className="text-[22px] font-black tracking-tight text-nearBlack">Agent Timeline</h2>
        <p className="mt-1 text-[13px] text-secondaryGray">
          Execution path generated by the multi-agent system. Click any stage to inspect the reasoning.
        </p>
      </div>

      <div className="rounded-[20px] max-w-5xl mx-auto border border-borderGray bg-pureWhite p-5 shadow-card">
        {/* Summary Stats */}
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {[
            { label: "Workflow path", value: humanizeLabel(trace?.current_branch) },
            { label: "Latest stage",  value: humanizeLabel(trace?.terminal_stage) },
            { label: "Strategy",      value: humanizeLabel(trace?.selected_strategy) },
            { label: "Status",        value: humanizeLabel(trace?.execution_status) },
          ].map((item) => (
            <div key={item.label} className="rounded-xl border border-borderGray/30 bg-lightSurface/60 px-3 py-2.5">
              <div className="text-[9px] font-bold uppercase tracking-widest text-secondaryGray">{item.label}</div>
              <div className="mt-1 text-[13px] font-black text-nearBlack truncate">{item.value}</div>
            </div>
          ))}
        </div>

        {/* Route Decisions */}
        {trace?.route_decisions.length ? (
          <div className="mt-4 flex flex-wrap gap-2">
            {trace.route_decisions.map((route) => (
              <span
                key={`${route.from_node}-${route.to_node}-${route.outcome}`}
                className="rounded-full border border-borderGray bg-lightSurface px-3 py-1.5 text-[11px] font-semibold text-secondaryGray"
                title={route.reason}
              >
                {humanizeNode(route.from_node)}{" "}
                <ChevronRight className="inline h-3 w-3" />{" "}
                {humanizeNode(route.to_node)}
              </span>
            ))}
          </div>
        ) : null}

        {/* Timeline */}
        {displayedSteps.length === 0 ? (
          <div className="mt-6 rounded-xl border border-borderGray bg-lightSurface px-5 py-8 text-center text-[13px] italic text-secondaryGray">
            Generate recommendations or run a simulation to populate the agent timeline.
          </div>
        ) : (
          <div className="relative mt-8 pb-4">
            {/* Center spine line */}
            <div className="absolute left-1/2 top-0 bottom-0 w-[2px] -translate-x-1/2 bg-gradient-to-b from-borderGray via-borderGray/60 to-transparent" />

            <div className="space-y-0">
              {displayedSteps.map((step, index) => {
                const visual = agentVisual(step.agent);
                const isSelected = index === selectedStepIndex;
                const isActive = index === latestVisibleStepIndex && (Boolean(actionLoading) || refreshing || !executionComplete);
                const Icon = visual.Icon;
                // Even index → card on LEFT, popover on RIGHT
                // Odd index  → card on RIGHT, popover on LEFT
                const isLeft = index % 2 === 0;

                return (
                  <Popover.Root
                    key={`${step.agent}-${step.started_at}`}
                    open={isSelected}
                    onOpenChange={(open) => {
                      if (open) onSelectStep(index);
                      else onSelectStep(-1);
                    }}
                  >
                    {/* Full-width row: [card slot] [dot] [card slot] */}
                    <div className={`relative grid grid-cols-[1fr_auto_1fr] items-center gap-0`}>

                      {/* LEFT SLOT */}
                      <div className="flex justify-end pr-6 w-full">
                        {isLeft ? (
                          <Popover.Anchor asChild>
                            <button
                              type="button"
                              onClick={() => onSelectStep(isSelected ? -1 : index)}
                              className={`w-full text-left rounded-[16px] border bg-pureWhite p-4 shadow-card transition-all hover:shadow-hover ${
                                isSelected ? `${visual.selectedClass} border-[2px]` : "border-borderGray"
                              }`}
                            >
                              <StepCardContent step={step} index={index} visual={visual} isActive={isActive} />
                            </button>
                          </Popover.Anchor>
                        ) : (
                          <div className="w-full" />
                        )}
                      </div>

                      {/* CENTER DOT */}
                      <button
                        type="button"
                        onClick={() => onSelectStep(isSelected ? -1 : index)}
                        className={`relative z-10 flex h-11 w-11 shrink-0 items-center justify-center rounded-full border-[3px] border-pureWhite shadow-card transition-transform hover:scale-110 ${visual.bubbleClass}`}
                      >
                        <Icon size={18} className={isActive ? "animate-pulse" : ""} />
                      </button>

                      {/* RIGHT SLOT */}
                      <div className="flex justify-start pl-6 w-full">
                        {!isLeft ? (
                          <Popover.Anchor asChild>
                            <button
                              type="button"
                              onClick={() => onSelectStep(isSelected ? -1 : index)}
                              className={`w-full text-left rounded-[16px] border bg-pureWhite p-4 shadow-card transition-all hover:shadow-hover ${
                                isSelected ? `${visual.selectedClass} border-[2px]` : "border-borderGray"
                              }`}
                            >
                              <StepCardContent step={step} index={index} visual={visual} isActive={isActive} />
                            </button>
                          </Popover.Anchor>
                        ) : (
                          <div className="w-full" />
                        )}
                      </div>
                    </div>

                    {/* Popover appears on the OPPOSITE side of the card */}
                    <Popover.Portal>
                      <Popover.Content
                        className="z-50 w-[420px] rounded-[20px] border border-borderGray bg-pureWhite shadow-2xl outline-none"
                        sideOffset={12}
                        side={isLeft ? "right" : "left"}
                        align="start"
                        onInteractOutside={() => onSelectStep(-1)}
                        onEscapeKeyDown={() => onSelectStep(-1)}
                      >
                        <StageDetail selectedStep={step} />
                      </Popover.Content>
                    </Popover.Portal>
                  </Popover.Root>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </section>
  );
}

// ── Sub-component: Card content (reused in both Left and Right slot) ──
function StepCardContent({ step, index, visual, isActive }: {
  step: AgentStepView;
  index: number;
  visual: ReturnType<typeof agentVisual>;
  isActive: boolean;
}) {
  return (
    <>
      <div className="flex flex-wrap items-center gap-1.5 mb-2">
        <span className="rounded bg-nearBlack px-1.5 py-0.5 text-[9px] font-black uppercase text-pureWhite">
          Step {index + 1}
        </span>
        <span className="rounded border border-borderGray px-1.5 py-0.5 text-[9px] font-bold uppercase text-secondaryGray">
          {tracePhase(step.agent)}
        </span>
        {step.llm_used && (
          <span className="rounded bg-rausch/10 px-1.5 py-0.5 text-[9px] font-bold uppercase text-rausch">AI</span>
        )}
        {isActive && (
          <span className="rounded bg-amber-100 px-1.5 py-0.5 text-[9px] font-bold uppercase text-amber-700">ACTIVE</span>
        )}
      </div>
      <h3 className="text-[15px] font-bold text-nearBlack">{humanizeNode(step.agent)}</h3>
      <div className={`mt-2.5 rounded-[10px] border border-borderGray/50 bg-lightSurface/60 p-3 border-l-[3px] ${visual.accentClass}`}>
        <p className="text-[13px] font-medium text-nearBlack line-clamp-2">{step.summary}</p>
        <p className="mt-1 text-[11px] text-secondaryGray">
          {step.completed_at ? "Completed → handed off." : "In progress..."}
        </p>
      </div>
    </>
  );
}
